sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

script:
  - sfdx force:auth:jwt:grant --clientid 3MVG9n_HvETGhr3CgaiBB_9civCPcrE_QHB01xffhnoRbhDDxEOElx2kYnDfN0otlZl2yO1gSQEeZSnMGU2Vg --username test-ncxsqf3aok8i@example.com --jwtkeyfile certificates/server.key --setalias target_org --instanceurl https://test.salesforce.com;
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ];
      then
        sfdx force:source:deploy -p ./force-app -u target_org --checkonly;
      else
        sfdx force:source:deploy -p ./force-app -u target_org;
        fi

branches:
  only:
    - master